"""Per-instance egress-allowlist rendering.

Phase 12 (slice 15). The Phase 9 egress-proxy ships with a static
deployment-wide allowlist at ``docker/egress-proxy/egress-allowlist.conf``
(``FilterDefaultDeny Yes`` with explicit-host regex entries). The
manifest's per-challenge ``container.egress_allowlist`` is captured
into ``Challenge.docker_config["egress_allowlist"]`` and persisted on
``ChallengeInstance`` rows, but until this slice it had no effect on
the proxy filter. This module renders the *union* of all currently-
active ``egress-proxied`` instances' allowlists into a tinyproxy
``Filter`` config, ready to be reloaded by the proxy.

**Hot-reload is operator-coordinated.** The renderer writes the
file; reloading tinyproxy (``SIGHUP`` to the running process inside
the egress-proxy container, or a restart) is a deployment concern
the operator owns. The CLI in ``app.tools.render_egress_allowlist``
exits 0 on a successful write so a wrapper script can chain the
reload step.

Per-instance rendering rules:

* Each FQDN in an active instance's allowlist becomes a single
  regex line ``^<escaped-fqdn>$``.
* Wildcard subdomain entries (``*.example.com``) become
  ``^.+\\.example\\.com$``.
* The output is sorted, de-duplicated, and starts with a generated-
  marker comment so operators don't hand-edit the rendered file.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, List, Sequence

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Challenge, ChallengeInstance, InstanceStatus

logger = structlog.get_logger()


_GENERATED_MARKER = "# generated by app.services.orchestration.egress — do not hand-edit"
_HEADER_TIMESTAMP_FMT = "%Y-%m-%dT%H:%M:%S%z"


@dataclass(frozen=True)
class _ActiveInstance:
    instance_id: int
    challenge_slug: str
    allowlist: tuple[str, ...]


@dataclass(frozen=True)
class RenderResult:
    """Aggregate result of a render pass."""

    rendered: str
    instance_count: int
    fqdn_count: int
    rules: List[str] = field(default_factory=list)


def _normalise_fqdn(raw: str) -> str:
    return raw.strip().lower()


def _fqdn_to_regex(fqdn: str) -> str:
    """Convert a single allowlist entry to a tinyproxy filter regex.

    * ``*.example.com`` → ``^.+\\.example\\.com$``
    * ``api.example.com`` → ``^api\\.example\\.com$``
    * empty / pure-whitespace → returns ``""`` (caller filters).
    """

    fqdn = _normalise_fqdn(fqdn)
    if not fqdn:
        return ""
    if fqdn.startswith("*."):
        suffix = fqdn[2:]
        if not suffix:
            return ""
        return f"^.+\\.{re.escape(suffix)}$"
    return f"^{re.escape(fqdn)}$"


def render_allowlist_text(
    instances: Sequence[_ActiveInstance],
    *,
    now: datetime | None = None,
) -> RenderResult:
    """Render the union of every active instance's allowlist."""

    seen: set[str] = set()
    rules: List[str] = []
    fqdn_count = 0
    for inst in instances:
        for fqdn in inst.allowlist:
            regex = _fqdn_to_regex(fqdn)
            if not regex:
                continue
            if regex in seen:
                continue
            seen.add(regex)
            rules.append(regex)
            fqdn_count += 1

    rules.sort()
    timestamp = (now or datetime.now(timezone.utc)).strftime(_HEADER_TIMESTAMP_FMT)
    header = [
        _GENERATED_MARKER,
        f"# generated_at: {timestamp}",
        f"# active_instances: {len(instances)}",
        f"# unique_fqdns: {fqdn_count}",
        "#",
        "# tinyproxy ``FilterDefaultDeny Yes`` is in effect; lines below",
        "# are the only host patterns reachable from egress-proxied",
        "# instances.",
        "",
    ]
    body_lines: List[str] = list(rules)
    text = "\n".join(header + body_lines + [""])
    return RenderResult(
        rendered=text,
        instance_count=len(instances),
        fqdn_count=fqdn_count,
        rules=list(rules),
    )


async def collect_active_instances(
    db: AsyncSession,
) -> List[_ActiveInstance]:
    """Return every running egress-proxied instance with its allowlist.

    Joins ``challenge_instances`` to ``challenges`` so the per-
    challenge ``docker_config["egress_allowlist"]`` ride along.
    Filters out instances whose status is anything but ``running``
    and whose ``applied_profile`` is not ``"egress-proxied"`` —
    other profiles either don't use the proxy at all (default-strict)
    or run with no outbound network (malware-sandbox).
    """

    rows = (
        await db.execute(
            select(ChallengeInstance, Challenge)
            .join(Challenge, Challenge.id == ChallengeInstance.challenge_id)
            .where(
                ChallengeInstance.status == InstanceStatus.running,
                ChallengeInstance.applied_profile == "egress-proxied",
            )
            .order_by(ChallengeInstance.id.asc())
        )
    ).all()

    out: List[_ActiveInstance] = []
    for instance, challenge in rows:
        allowlist = list(
            (challenge.docker_config or {}).get("egress_allowlist") or []
        )
        out.append(
            _ActiveInstance(
                instance_id=instance.id,
                challenge_slug=challenge.slug,
                allowlist=tuple(_normalise_fqdn(f) for f in allowlist),
            )
        )
    return out


async def render_to_file(
    db: AsyncSession,
    target: Path | str,
    *,
    now: datetime | None = None,
) -> RenderResult:
    """Render the active-instance allowlist to ``target`` atomically.

    Writes via temp-file + ``os.replace`` so a tinyproxy reload that
    fires during the write never sees a half-written file.
    """

    target = Path(target)
    instances = await collect_active_instances(db)
    result = render_allowlist_text(instances, now=now)

    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(result.rendered, encoding="utf-8")
    tmp.replace(target)
    return result


_DEFAULT_PROXY_CONTAINER = "siege-egress-proxy"
_DEFAULT_FILTER_PATH = Path("/etc/tinyproxy/egress-allowlist.conf")
_RELOAD_SIGNAL = "SIGHUP"


def signal_egress_reload(
    docker_client_obj,
    *,
    proxy_container_name: str = _DEFAULT_PROXY_CONTAINER,
) -> bool:
    """Send SIGHUP to the egress-proxy container so tinyproxy re-reads
    its filter file.

    Best-effort: returns ``True`` on a successful kill call, ``False``
    on any failure (container missing, signal rejected, docker socket
    unreachable). Failures are *never* propagated to the caller — a
    flapping egress proxy must not 500 a flag submission or block an
    instance teardown. The launcher / cleanup paths log the outcome
    via ``structlog`` and continue.

    The docker-socket-proxy ACL needs ``CONTAINERS=1`` + ``POST=1``
    for the ``POST /containers/{id}/kill?signal=SIGHUP`` endpoint to
    be reachable; the platform's compose has these set since Phase 9.
    """

    try:
        container = docker_client_obj.containers.get(proxy_container_name)
        container.kill(signal=_RELOAD_SIGNAL)
        logger.info(
            "egress proxy reloaded",
            container=proxy_container_name,
            signal=_RELOAD_SIGNAL,
        )
        return True
    except Exception as exc:  # noqa: BLE001 — best-effort
        logger.warning(
            "egress proxy reload failed",
            container=proxy_container_name,
            error=f"{type(exc).__name__}: {exc}",
        )
        return False


async def refresh_proxy_allowlist(
    db: AsyncSession,
    docker_client_obj=None,
    *,
    target: Path | str | None = None,
    proxy_container_name: str = _DEFAULT_PROXY_CONTAINER,
) -> RenderResult | None:
    """Render the active allowlist + signal tinyproxy to reload.

    Used by ``launch_instance`` / ``cleanup_expired`` / ``stop_instance``
    after any state change involving an ``egress-proxied`` instance.
    Best-effort: returns the :class:`RenderResult` on success or
    ``None`` if rendering or the signal failed. Caller logs the
    outcome and proceeds — egress-proxy maintenance must not block
    the orchestration flow.

    ``target`` defaults to ``settings.EGRESS_FILTER_PATH`` if set,
    otherwise the conventional ``/etc/tinyproxy/egress-allowlist.conf``.
    Operators who don't share a volume with the proxy can point this
    at a host-writable path and run their own reload mechanism — the
    signal step still fires (and harmlessly fails) on every refresh.
    """

    from app.config import get_settings

    settings = get_settings()
    target_path = Path(
        target
        or getattr(settings, "EGRESS_FILTER_PATH", None)
        or _DEFAULT_FILTER_PATH
    )

    try:
        result = await render_to_file(db, target_path)
    except Exception as exc:  # noqa: BLE001 — best-effort
        logger.warning(
            "egress allowlist render failed",
            target=str(target_path),
            error=f"{type(exc).__name__}: {exc}",
        )
        return None

    # Only signal if we got a real docker client. Tests pass a stub;
    # production resolves via the platform's long-lived client.
    if docker_client_obj is not None:
        signal_egress_reload(
            docker_client_obj, proxy_container_name=proxy_container_name
        )
    return result


__all__ = [
    "RenderResult",
    "_fqdn_to_regex",
    "collect_active_instances",
    "refresh_proxy_allowlist",
    "render_allowlist_text",
    "render_to_file",
    "signal_egress_reload",
]
