server {
    listen 8080;
    server_name localhost;

    access_log /dev/stdout;
    error_log /dev/stderr;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /capture.pcap {
        add_header Content-Disposition 'attachment; filename="capture.pcap"';
        add_header Content-Type application/octet-stream;
    }
}
