#!/usr/bin/env bash
# Sprint 1 — image digest refresh helper.
#
# Resolves each infra image referenced in ``docker-compose.yml`` to
# its current sha256 digest and writes a sibling
# ``docker-compose.digests.yml`` override that pins them. Operators
# include both files when running ``make prod`` so a rebuild can't
# silently pull a different image under the same tag.
#
# Run on a build host with network access (the production runner
# itself is fine). Re-run quarterly or on receipt of a CVE
# advisory for any of the pinned images.
#
# Output:
#
#     services:
#       nginx:
#         image: nginx:1.25-alpine@sha256:...
#       db:
#         image: postgres:16-alpine@sha256:...
#       …
#
# Usage:
#
#     ./scripts/refresh-image-digests.sh
#     git diff docker-compose.digests.yml   # review
#     git commit -m "chore(infra): refresh image digests"

set -euo pipefail

cd "$(dirname "$0")/.."

# Images we pin. Any image we *build* (api, dashboard) is content-
# addressed by Dockerfile + source already and doesn't appear here.
IMAGES=(
    "nginx:1.25-alpine"
    "postgres:16-alpine"
    "redis:7-alpine"
    "docker:24-dind"
    "tecnativa/docker-socket-proxy:0.1.2"
    "lscr.io/linuxserver/wireguard:latest"
)

# Map each image to the compose-service that uses it. Keep in sync
# with docker-compose.yml.
declare -A SERVICE_FOR
SERVICE_FOR["nginx:1.25-alpine"]="nginx"
SERVICE_FOR["postgres:16-alpine"]="db"
SERVICE_FOR["redis:7-alpine"]="redis"
SERVICE_FOR["docker:24-dind"]="orchestrator"
SERVICE_FOR["tecnativa/docker-socket-proxy:0.1.2"]="docker-proxy"
SERVICE_FOR["lscr.io/linuxserver/wireguard:latest"]="vpn"

OUTPUT="docker-compose.digests.yml"

{
    echo "# Generated by scripts/refresh-image-digests.sh — do not hand-edit."
    echo "# Refresh quarterly or on CVE advisory; commit the diff."
    echo "# Use with:  docker compose -f docker-compose.yml -f docker-compose.digests.yml -f docker-compose.prod.yml up -d"
    echo ""
    echo "services:"

    for image in "${IMAGES[@]}"; do
        service="${SERVICE_FOR[$image]}"
        echo "  ${service}:"
        echo -n "    image: "

        # ``docker buildx imagetools inspect`` returns the manifest
        # digest without pulling the image. Falls back to ``docker
        # pull`` + ``docker inspect`` if buildx isn't available.
        if command -v docker >/dev/null && docker buildx version >/dev/null 2>&1; then
            digest=$(docker buildx imagetools inspect "$image" \
                --format '{{ .Manifest.Digest }}' 2>/dev/null || true)
        fi

        if [ -z "${digest:-}" ]; then
            echo "ERROR: could not resolve digest for ${image}" >&2
            echo "${image}  # FAILED TO RESOLVE — keep tag, retry"
            continue
        fi

        echo "${image}@${digest}"
    done
} > "${OUTPUT}"

echo "wrote ${OUTPUT}"
echo "review with: git diff ${OUTPUT}"
